peso = float(input("Digite o peso da pessoa: "))
novo_peso_engordar = peso + (peso * 0.15)
novo_peso_emagrecer = peso - (peso * 0.20)
print("O novo peso se a pessoa engordar 15% é:", novo_peso)
print("O novo peso se a pessoa emagrecer 20% é:", novo_peso_emagrecer)